### ISSUE TITLE
Ability to edit URL before opening them

### ISSUE THREAD

**Issue by NikunjKhangwal** [LinkSheet/LinkSheet#317]
### Feature description

Pretty much the title. It would be nice to be able to edit url before opening (and sharing) them in case you want to make any changes.

**Comment by 1fexd** [comment]
How would you expect this to work when "processing" is involved? For example, if you tap a link and LinkSheet opens, but then starts following redirects before displaying the apps that can handle that link, would you want to edit the url before (e.g. by first showing a popup where you can edit it), or is editing from the bottom sheet itself (when the apps are already shown) also fine? Because I think that might be a little awkward

**Comment by NikunjKhangwal** [comment]
I think editing in sheet item would be better. Pop up might annoy users.

**Comment by 1fexd** [comment]
I'd agree, closing this in favor of #403
